### ISSUE TITLE
CI job does not fail on errors

### ISSUE THREAD

**Issue by Bai-Yingjie** [tuliren/publish-gitbook#4]
Hi,
I am using pubish-gitbook action in my repo:
```yaml
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Publish Gitbook
        uses: tuliren/publish-gitbook@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

In the CI job, I found the job showed false success but actually there were errors.
https://github.com/Bai-Yingjie/Bai-Yingjie.github.io/actions/runs/3270326269/jobs/5378819258

I looked the code [entrypoint.sh](https://github.com/tuliren/publish-gitbook/blob/master/entrypoint.sh), can we put `set -e` earlier than `gitbook build` to catch errors?
